### ISSUE TITLE
node compatibility of /lib files

### ISSUE THREAD

**Issue by knownasilya** [minichate/ember-cli-tree-shake#5]
```
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/mapgeo.alpha1.appgeo.com/map/node_modules/ember-cli-tree-shake/index.js:9:30)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by minichate** [comment]
Hello!

What version of NodeJS are you using? I've really only tested against Node 6, but if you're using a relatively recent version I can see if I can support it too.

**Comment by knownasilya** [comment]
4.4.7, which is still in the ember-cli support roadmap (basically anything after 0.12)

**Comment by minichate** [comment]
Ok thanks! I'll see what I can do
